id: IDF6693A6
legacy_id: P009255
ocr_import_info:
  bdrc_scan_id: W4CZ1044
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T00:09:43'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:22:52.010031+00:00'
last_modified: 2022-09-04 02:23:02.134890
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ1044
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ1044
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལམ་རིམ་ཆུང་ངུ།
  author: ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.4639701987039421
  ocr_word_median_confidence_index: 0.3700000047683716
quality: null
bases:
  I1KG13520:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13520
      total_pages: 316
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13520.txt
    statistics:
      ocr_word_median_confidence_index: 0.3700000047683716
      ocr_word_mean_confidence_index: 0.4639701987039421
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
